name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        run: pip install pipenv
      - name: Run tests
        run: |
          pipenv install 
          pipenv install --dev
      - name: Open Pipenv shell
        run: pipenv shell
      - name: Run Tests
        run: pytest
